---
abstract: 'a more knowledgeable perldoc'
author:
  - 'Marcel Gruenauer <marcel@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.11
generated_by: 'Dist::Zilla version 1.100660'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-perlzonji
provides:
  App::perlzonji:
    file: lib/App/perlzonji.pm
    version: 1.100710
requires:
  Carp: 0
  English: 0
  File::Find: 0
  File::Temp: 0
  Pod::Usage::CommandLine: 0
  Scalar::Util: 0
  Test::More: 0
  perl: 5.008
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=App-perlzonji
  homepage: http://search.cpan.org/dist/App-perlzonji/
  repository: http://github.com/hanekomu/App-perlzonji
version: 1.100710
