---
abstract: 'A more knowledgeable perldoc'
author:
  - 'Marcel Gruenauer <marcel@cpan.org>'
build_requires:
  Carp: 0
  English: 0
  File::Find: 0
  File::Temp: 0
  Scalar::Util: 0
  Test::More: 0.94
configure_requires:
  ExtUtils::MakeMaker: 6.31
generated_by: 'Dist::Zilla version 2.100991'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-perlzonji
provides:
  App::perlzonji:
    file: lib/App/perlzonji.pm
    version: 1.101000
  App::perlzonji::Plugin::FoundIn:
    file: lib/App/perlzonji/Plugin/FoundIn.pm
    version: 1.101000
  App::perlzonji::Plugin::Label:
    file: lib/App/perlzonji/Plugin/Label.pm
    version: 1.101000
  App::perlzonji::Plugin::SpecialPackages:
    file: lib/App/perlzonji/Plugin/SpecialPackages.pm
    version: 1.101000
  App::perlzonji::Plugin::UseModule:
    file: lib/App/perlzonji/Plugin/UseModule.pm
    version: 1.101000
recommends: {}
requires:
  Class::Trigger: 0
  Module::Pluggable: 0
  Pod::Usage::CommandLine: 0
  perl: 5.008
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=App-perlzonji
  homepage: http://search.cpan.org/dist/App-perlzonji/
  repository: http://github.com/hanekomu/App-perlzonji
version: 1.101000
