---
abstract: 'A more knowledgeable perldoc'
author:
  - 'Marcel Gruenauer <marcel@cpan.org>'
build_requires:
  Capture::Tiny: 0
  Carp: 0
  English: 0
  File::Find: 0
  File::Temp: 0
  Scalar::Util: 0
  Test::More: 0.94
configure_requires:
  ExtUtils::MakeMaker: 6.58
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.113640'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-perlzonji
no_index:
  directory:
    - t
    - inc
requires:
  Class::Trigger: 0
  Getopt::Long: 0
  Module::Pluggable: 0
  Pod::Usage: 0
  Time::HiRes: 0
  autodie: 0
  strict: 0
  warnings: 0
version: 1.20
